version: '3'

services:
  backend:
    image: drissb45/2023-09-wns-blanc-mailcraft-backend:latest
    env.file: .env.backend
    ports:
      - 4000:3001

  frontend:
    image: drissb45/2023-09-wns-blanc-mailcraft-frontend:latest
    env.file: .env.frontend
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    env_file: .env.db
    volumes:
      - ./dbData:/var/lib/postgresql/data/customDataFolder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
