version: "3"

services:
  backend:
    build: ./backend
    ports:
      - 4000:3001
    volumes:
      - ./backend/package.json:/app/package.json:rw
      - ./backend/.env:/app/.env:rw
      - ./backend/src/:/app/src/:rw
    environment:
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src/:/app/src/:rw
      - ./frontend/.env.local:/app/.env.local:rw
      - ./frontend/package.json:/app/package.json:rw
      - ./frontend/postcss.config.js:/app/postcss.config.js:rw
      - ./frontend/tailwind.config.js:/app/tailwind.config.js:rw
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: customDataFolder
    volumes:
      - ./dbData/:/var/lib/postgresql/data/customDataFolder
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    ports:
      - 8080:8080
